# Generated by Django 3.1.4 on 2021-03-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Whatsapp', 'Whatsapp'), ('Facebook', 'Facebook')], max_length=100),
        ),
    ]
