# Generated by Django 3.1.4 on 2021-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210414_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Whatsapp', 'Whatsapp'), ('Facebook', 'Facebook')], max_length=100),
        ),
    ]
